import type { LineAnnotation, LineNode, LineSegment } from "../annotationTypes";
import type { Point } from "../../drawings/workspace/viewportTypes";

export const lineEpsilon=1e-6;
export function lineNode(line:LineAnnotation,id:string){return line.nodes.find(node=>node.id===id)}
export function segmentNodes(line:LineAnnotation,segment:LineSegment){const start=lineNode(line,segment.startNodeId),end=lineNode(line,segment.endNodeId);return start&&end?{start,end}:undefined}
export function segmentLength(line:LineAnnotation,segmentId:string){const segment=line.segments.find(item=>item.id===segmentId),nodes=segment&&segmentNodes(line,segment);return nodes?Math.hypot(nodes.end.x-nodes.start.x,nodes.end.y-nodes.start.y):0}
export function cornerAngle(line:LineAnnotation,nodeId:string){const index=line.nodeOrder.indexOf(nodeId);if(index<=0||index>=line.nodeOrder.length-1)return undefined;const a=lineNode(line,line.nodeOrder[index-1]),b=lineNode(line,nodeId),c=lineNode(line,line.nodeOrder[index+1]);if(!a||!b||!c)return undefined;const v1={x:a.x-b.x,y:a.y-b.y},v2={x:c.x-b.x,y:c.y-b.y},den=Math.hypot(v1.x,v1.y)*Math.hypot(v2.x,v2.y);if(den<=lineEpsilon)return undefined;return Math.acos(Math.max(-1,Math.min(1,(v1.x*v2.x+v1.y*v2.y)/den)))*180/Math.PI}
export function displayedAngle(angle:number,side:"acute"|"obtuse"){const acute=Math.min(angle,180-angle);return side==="acute"?acute:180-acute}
export function isRightAngle(angle:number,tolerance=.25){return Math.abs(angle-90)<=tolerance}
export type ConstraintResult={ok:true;line:LineAnnotation}|{ok:false;reason:string};
export function setSegmentLength(line:LineAnnotation,segmentId:string,lengthWorld:number):ConstraintResult{if(!(lengthWorld>lineEpsilon))return{ok:false,reason:"Length must be greater than zero."};const segmentIndex=line.segments.findIndex(item=>item.id===segmentId),segment=line.segments[segmentIndex],pair=segment&&segmentNodes(line,segment);if(segmentIndex<0||!pair)return{ok:false,reason:"Segment was not found."};if(pair.start.locked&&pair.end.locked)return{ok:false,reason:"Both segment endpoints are locked."};const current=Math.hypot(pair.end.x-pair.start.x,pair.end.y-pair.start.y);if(current<=lineEpsilon)return{ok:false,reason:"A zero-length segment cannot be edited."};const ux=(pair.end.x-pair.start.x)/current,uy=(pair.end.y-pair.start.y)/current;
 if(pair.start.locked&&!pair.end.locked){return translateOrderedRange(line,segmentIndex+1,{x:pair.start.x+ux*lengthWorld-pair.end.x,y:pair.start.y+uy*lengthWorld-pair.end.y})}
 const desired={x:pair.start.x+ux*lengthWorld,y:pair.start.y+uy*lengthWorld};return translateOrderedRange(line,segmentIndex+1,{x:desired.x-pair.end.x,y:desired.y-pair.end.y});}
function translateOrderedRange(line:LineAnnotation,startIndex:number,delta:Point):ConstraintResult{const ids=line.nodeOrder.slice(startIndex),locked=ids.find(id=>lineNode(line,id)?.locked);if(locked)return{ok:false,reason:"A locked downstream node prevents this change."};return{ok:true,line:{...line,nodes:line.nodes.map(node=>ids.includes(node.id)?{...node,x:node.x+delta.x,y:node.y+delta.y}:node),updatedAt:new Date().toISOString()}}}
export function setCornerAngle(line:LineAnnotation,nodeId:string,degrees:number):ConstraintResult{if(!(degrees>0&&degrees<180))return{ok:false,reason:"Angle must be between 0° and 180°."};const index=line.nodeOrder.indexOf(nodeId);if(index<=0||index>=line.nodeOrder.length-1)return{ok:false,reason:"Only internal nodes have editable angles."};const pivot=lineNode(line,nodeId),previous=lineNode(line,line.nodeOrder[index-1]),next=lineNode(line,line.nodeOrder[index+1]);if(!pivot||!previous||!next)return{ok:false,reason:"Angle geometry is incomplete."};const downstream=line.nodeOrder.slice(index+1);if(downstream.some(id=>lineNode(line,id)?.locked))return{ok:false,reason:"A locked downstream node prevents this rotation."};const base=Math.atan2(previous.y-pivot.y,previous.x-pivot.x),current=Math.atan2(next.y-pivot.y,next.x-pivot.x),cross=(previous.x-pivot.x)*(next.y-pivot.y)-(previous.y-pivot.y)*(next.x-pivot.x),target=base+(cross>=0?1:-1)*degrees*Math.PI/180,delta=target-current,cos=Math.cos(delta),sin=Math.sin(delta);return{ok:true,line:{...line,nodes:line.nodes.map(node=>downstream.includes(node.id)?{...node,x:pivot.x+(node.x-pivot.x)*cos-(node.y-pivot.y)*sin,y:pivot.y+(node.x-pivot.x)*sin+(node.y-pivot.y)*cos}:node),updatedAt:new Date().toISOString()}}}
export function hasZeroLengthSegment(line:LineAnnotation){return line.segments.some(segment=>segmentLength(line,segment.id)<=lineEpsilon)}
export function breakLineAtNode(line:LineAnnotation,nodeId:string,idFactory:()=>string):[LineAnnotation,LineAnnotation]|undefined{const index=line.nodeOrder.indexOf(nodeId);if(index<=0||index>=line.nodeOrder.length-1)return;const make=(order:string[]):LineAnnotation=>{const nodeIds=new Map(order.map(id=>[id,id===nodeId?idFactory():id]));const nodes=order.map(id=>({...lineNode(line,id)!,id:nodeIds.get(id)!}));const segments:LineSegment[]=nodes.slice(0,-1).map((node,i)=>({id:idFactory(),startNodeId:node.id,endNodeId:nodes[i+1].id}));return{...line,id:idFactory(),nodeOrder:nodes.map(n=>n.id),nodes,segments,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}};return[make(line.nodeOrder.slice(0,index+1)),make(line.nodeOrder.slice(index))]}
