import { useRef } from "react";
import type { ImageAnnotation } from "../annotationTypes";
import type { Point } from "../../drawings/workspace/viewportTypes";

export type ImageEditHandle="move"|"rotate"|"corner0"|"corner1"|"corner2"|"corner3"|"crop0"|"crop1"|"crop2"|"crop3";
type Props={image:ImageAnnotation;url?:string;scale:number;isSelected:boolean;isEditable:boolean;editMode?:"distort"|"crop";onSelect(id:string):void;onEdit(id:string):void;onStart?(id:string,h:ImageEditHandle,e:React.PointerEvent<SVGElement>):void;onUpdate?(id:string,h:ImageEditHandle,e:React.PointerEvent<SVGElement>):void;onEnd?(id:string,h:ImageEditHandle,e:React.PointerEvent<SVGElement>):void};

export function getImageCorners(image:ImageAnnotation):[Point,Point,Point,Point]{return image.corners??[{x:image.position.x,y:image.position.y},{x:image.position.x+image.width,y:image.position.y},{x:image.position.x+image.width,y:image.position.y+image.height},{x:image.position.x,y:image.position.y+image.height}]}
export function quadPoint(corners:[Point,Point,Point,Point],u:number,v:number){const [a,b,c,d]=corners;return{x:(1-u)*(1-v)*a.x+u*(1-v)*b.x+u*v*c.x+(1-u)*v*d.x,y:(1-u)*(1-v)*a.y+u*(1-v)*b.y+u*v*c.y+(1-u)*v*d.y}}

export function ImageRenderer({image,url,scale,isEditable,editMode,onSelect,onEdit,onStart,onUpdate,onEnd}:Props){
 const timer=useRef<number|undefined>(undefined);const start=useRef<Point|undefined>(undefined);const s=scale||1,corners=getImageCorners(image),cropRect=image.cropRect;
 const cropCorners:[Point,Point,Point,Point]=cropRect?[{x:cropRect.x,y:cropRect.y},{x:cropRect.x+cropRect.width,y:cropRect.y},{x:cropRect.x+cropRect.width,y:cropRect.y+cropRect.height},{x:cropRect.x,y:cropRect.y+cropRect.height}]:corners;
 const cancel=()=>{if(timer.current)clearTimeout(timer.current);timer.current=undefined;start.current=undefined};
 const begin=(handle:ImageEditHandle)=>(event:React.PointerEvent<SVGElement>)=>{event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);onStart?.(image.id,handle,event)};
 if(!url)return null;const visibleCorners=editMode==="crop"?cropCorners:corners;
 return <g className={`image-object ${isEditable?"is-editable":""} image-object--${editMode??"browse"}`}>
   {editMode==="crop"?<><MappedImage id={`${image.id}-shade`} url={url} source={unitSquare} destination={corners} opacity={.28}/><ClippedMappedImage id={`${image.id}-crop`} url={url} destination={corners} cropRect={cropRect}/></>:<ClippedMappedImage id={`${image.id}-visible`} url={url} destination={corners} cropRect={cropRect}/>} 
   <polygon className="image-hit-zone" data-annotation-hit="true" points={visibleCorners.map(p=>`${p.x},${p.y}`).join(" ")} onPointerDown={event=>{onSelect(image.id);cancel();if(isEditable){begin("move")(event)}else{start.current={x:event.clientX,y:event.clientY};timer.current=window.setTimeout(()=>onEdit(image.id),500)}}} onPointerMove={event=>{if(isEditable){event.preventDefault();event.stopPropagation();onUpdate?.(image.id,"move",event)}else if(start.current&&Math.hypot(event.clientX-start.current.x,event.clientY-start.current.y)>10)cancel()}} onPointerUp={event=>{if(isEditable){event.stopPropagation();onEnd?.(image.id,"move",event)}cancel()}} onPointerCancel={cancel}/>
   {isEditable&&editMode==="distort"?<><polygon className="image-edit-outline" points={corners.map(p=>`${p.x},${p.y}`).join(" ")}/>{corners.map((p,index)=><Handle key={index} point={p} scale={s} onDown={begin(`corner${index}` as ImageEditHandle)} onMove={event=>onUpdate?.(image.id,`corner${index}` as ImageEditHandle,event)} onUp={event=>onEnd?.(image.id,`corner${index}` as ImageEditHandle,event)}/>)}</>:null}
   {isEditable&&editMode==="crop"?<><path className="image-crop-border" d={`${cropCorners.map((p,index)=>`${index?"L":"M"}${p.x} ${p.y}`).join(" ")} Z`}/>{cropCorners.map((p,index)=><Handle key={index} point={p} scale={s} onDown={begin(`crop${index}` as ImageEditHandle)} onMove={event=>onUpdate?.(image.id,`crop${index}` as ImageEditHandle,event)} onUp={event=>onEnd?.(image.id,`crop${index}` as ImageEditHandle,event)}/>)}</>:null}
 </g>
}

function MappedImage({id,url,source,destination,opacity=1}:{id:string;url:string;source:[Point,Point,Point,Point];destination:[Point,Point,Point,Point];opacity?:number}){const triangles:[[Point,Point,Point],[Point,Point,Point]]=[[source[0],source[1],source[2]],[source[0],source[2],source[3]]],targets:[[Point,Point,Point],[Point,Point,Point]]=[[destination[0],destination[1],destination[2]],[destination[0],destination[2],destination[3]]];return <g opacity={opacity}>{triangles.map((triangle,index)=>{const target=targets[index],matrix=affine(triangle,target),clip=`${id}-${index}`;return <g key={clip}><defs><clipPath id={clip}><polygon points={target.map(p=>`${p.x},${p.y}`).join(" ")}/></clipPath></defs><g clipPath={`url(#${clip})`}><image href={url} x="0" y="0" width="1" height="1" preserveAspectRatio="none" transform={`matrix(${matrix.join(" ")})`}/></g></g>})}</g>}
const unitSquare:[Point,Point,Point,Point]=[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}];
function ClippedMappedImage({id,url,destination,cropRect}:{id:string;url:string;destination:[Point,Point,Point,Point];cropRect?:{x:number;y:number;width:number;height:number}}){if(!cropRect)return <MappedImage id={id} url={url} source={unitSquare} destination={destination}/>;const clip=`${id}-rect`;return <g><defs><clipPath id={clip}><rect x={cropRect.x} y={cropRect.y} width={cropRect.width} height={cropRect.height}/></clipPath></defs><g clipPath={`url(#${clip})`}><MappedImage id={`${id}-mapped`} url={url} source={unitSquare} destination={destination}/></g></g>}
function affine(source:[Point,Point,Point],target:[Point,Point,Point]){const [p0,p1,p2]=source,[q0,q1,q2]=target,det=p0.x*(p1.y-p2.y)+p1.x*(p2.y-p0.y)+p2.x*(p0.y-p1.y)||1,solve=(v0:number,v1:number,v2:number)=>[(v0*(p1.y-p2.y)+v1*(p2.y-p0.y)+v2*(p0.y-p1.y))/det,(v0*(p2.x-p1.x)+v1*(p0.x-p2.x)+v2*(p1.x-p0.x))/det,(v0*(p1.x*p2.y-p2.x*p1.y)+v1*(p2.x*p0.y-p0.x*p2.y)+v2*(p0.x*p1.y-p1.x*p0.y))/det],x=solve(q0.x,q1.x,q2.x),y=solve(q0.y,q1.y,q2.y);return[x[0],y[0],x[1],y[1],x[2],y[2]]}
function Handle({point,scale,onDown,onMove,onUp}:{point:Point;scale:number;onDown(e:React.PointerEvent<SVGCircleElement>):void;onMove(e:React.PointerEvent<SVGCircleElement>):void;onUp(e:React.PointerEvent<SVGCircleElement>):void}){return <g className="edit-handle-group"><circle className="image-corner-handle" cx={point.x} cy={point.y} r={11/scale}/><circle className="edit-handle-hit" data-annotation-hit="true" cx={point.x} cy={point.y} r={24/scale} onPointerDown={onDown} onPointerMove={event=>{event.stopPropagation();onMove(event)}} onPointerUp={event=>{event.stopPropagation();onUp(event)}} onPointerCancel={onUp}/></g>}
