import { ArrowUpRight, FolderPlus, PencilRuler } from "lucide-react";
import { Brand } from "../../components/Brand";
import { BottomNavigation } from "../../components/BottomNavigation";
import { ProjectRow } from "../projects/ProjectRow";
import type { Project } from "../projects/projectTypes";
export function HomeScreen({ projects, onNewJob, onQuickDraw, onOpenProjects, onOpenProject }: { projects: Project[]; onNewJob: () => void; onQuickDraw: () => void; onOpenProjects: () => void; onOpenProject: (id: string) => void }) {
  const recent = [...projects].sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0,8);
  return <main className="pillar-page home-page"><header className="home-brand"><Brand/></header><div className="home-intro"><span className="technical-label">YOUR DIGITAL SITE NOTEBOOK</span><span className="local-indicator"><i/> LOCAL WORKSPACE</span></div><section className="pillar-quick-actions" aria-label="Quick actions"><button className="quick-action is-primary" onClick={onNewJob}><FolderPlus/><strong>NEW JOB</strong><span>Site notes, photos<br/>and drawings</span><ArrowUpRight className="quick-arrow"/></button><button className="quick-action" onClick={onQuickDraw}><PencilRuler/><strong>QUICK DRAW</strong><span>Choose a job.<br/>Capture an idea.</span><ArrowUpRight className="quick-arrow"/></button></section><div className="list-heading"><h1>RECENT PROJECTS</h1><button onClick={onOpenProjects}>VIEW ALL <ArrowUpRight size={15}/></button></div><section aria-label="Recent projects" className="job-list">{recent.map(p => <ProjectRow key={p.id} project={p} onOpen={() => onOpenProject(p.id)}/>)}{!recent.length ? <div className="notebook-empty"><FolderPlus/><h2>Good work starts with good notes.</h2><p>Create your first job, capture the details and take the whole notebook into a work order.</p><button className="primary-button" onClick={onNewJob}>Create your first job</button></div> : null}</section><p className="home-footnote">CAPTURE ON SITE. BUILD WITH CLARITY.</p><BottomNavigation active="home" onNavigate={tab => tab === "projects" ? onOpenProjects() : undefined}/></main>;
}
